//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapClient.MiServicioClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiServicioClient.IMiServicio")]
    public interface IMiServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/Sumar", ReplyAction="http://tempuri.org/IMiServicio/SumarResponse")]
        string Sumar(int a, int b, int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiServicio/Sumar", ReplyAction="http://tempuri.org/IMiServicio/SumarResponse")]
        System.Threading.Tasks.Task<string> SumarAsync(int a, int b, int c);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiServicioChannel : SoapClient.MiServicioClient.IMiServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiServicioClient : System.ServiceModel.ClientBase<SoapClient.MiServicioClient.IMiServicio>, SoapClient.MiServicioClient.IMiServicio {
        
        public MiServicioClient() {
        }
        
        public MiServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Sumar(int a, int b, int c) {
            return base.Channel.Sumar(a, b, c);
        }
        
        public System.Threading.Tasks.Task<string> SumarAsync(int a, int b, int c) {
            return base.Channel.SumarAsync(a, b, c);
        }
    }
}
